### ISSUE TITLE
Load test is crashing on start

### ISSUE THREAD

**Issue by vikulikov** [PrivateRookie/ws-tool#32]
```
cargo lt -- -p 300 --count 50000 -t 1 'ws://localhost:9002'
    Finished release [optimized] target(s) in 0.20s
     Running `target/release/examples/load_test -p 300 --count 50000 -t 1 'ws://localhost:9002'`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })', examples/load_test.rs:96:41
thread 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', examples/load_test.rs:89:58
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', examples/load_test.rs:99:53
```

**Comment by vikulikov** [comment]
It's actually error from server:
```
Entering direct command mode for peer tcp4:172.17.0.1:34064
Unhandled Error
Traceback (most recent call last):
  File "/opt/pypy/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/opt/pypy/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/opt/pypy/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/pypy/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/opt/pypy/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/opt/pypy/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/opt/pypy/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/opt/pypy/site-packages/autobahn/twisted/websocket.py", line 135, in dataReceived
    self._dataReceived(data)
  File "/opt/pypy/site-packages/autobahn/websocket/protocol.py", line 1315, in _dataReceived
    self.consumeData()
  File "/opt/pypy/site-packages/autobahn/websocket/protocol.py", line 1330, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/opt/pypy/site-packages/autobahn/websocket/protocol.py", line 1482, in processData
    return self.processDataHybi()
  File "/opt/pypy/site-packages/autobahn/websocket/protocol.py", line 1793, in processDataHybi
    fr = self.onFrameEnd()
  File "/opt/pypy/site-packages/autobahn/websocket/protocol.py", line 1920, in onFrameEnd
    self._onMessageEnd()
  File "/opt/pypy/site-packages/autobahn/twisted/websocket.py", line 163, in _onMessageEnd
    self.onMessageEnd()
  File "/opt/pypy/site-packages/autobahn/websocket/protocol.py", line 735, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/opt/pypy/site-packages/autobahn/twisted/websocket.py", line 166, in _onMessage
    self.onMessage(payload, isBinary)
  File "/opt/pypy/site-packages/autobahntestsuite/fuzzing.py", line 357, in onMessage
    raise Exception("binary command message")
exceptions.Exception: binary command message
```
Server launched with command `./scripts/start_autobahn_server.sh`

**Comment by PrivateRookie** [comment]
`cargo lt` should run with server in bench_xxx example, start_autobahn_server.sh is used to launch a python websocket server for  authbahn testsuit, you use run authbahn_xxx example to connect autobahn server

**Comment by vikulikov** [comment]
Thank you! It works.
